version: '2'

services:
  # This container is never builded - it's used only
  # for reusing configuration,
  meta:
    image: busybox # Necessary to make this container valid.
    environment:
      - MYSQL_USER=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  app:
    extends: meta
    image: drupal-boilerplate # Only needed to override "meta" image.
    build: ./docker
    hostname: app
    ports:
      - "80:80"
    cap_add:
      - ALL
    links:
      - database:database-host
    volumes:
        # 1 - Use ssh config from host.
        # 2 - Use git config from host.
        # 3 - Place app files.
      - $HOME/.ssh:/drupal/.ssh
      - $HOME/.gitconfig:/drupal/.gitconfig
      - $PWD:/drupal/app

  database:
    extends: meta
    image: mysql:5.6
    container_name: 'drupal-boilerplate-database'
    volumes:
      # Persist database outside container.
      - $PWD/.mysql/:/var/lib/mysql
